name: Bug Fix
description: Fixing a bug in the codebase
title: "[Bug]: "
labels: ["bug", "triage"]
projects: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for contributing and fixing this bug!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: true
  - type: textarea
    id: bug-issue
    attributes:
      label: Issue Id
      description: What issue are you fixing with this PR?
      placeholder: Give us the issue number or a link to the issue
      value: "https://github.com/mrlunchbox777/basic-setup/issues/50"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: A Description of the Bug Fix
      description: Please describe how this PR fixes the bug
      placeholder: Let us know what you did to fix the bug
      value: "This PR fixes the bug by adding a check for null values"
    validations:
      required: false
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce and Test
      description: How can we reproduce the bug you're fixing?
      placeholder: Give us a step-by-step guide to reproduce the bug. A link to steps in the issue is also acceptable.
      value: "1. Go to the homepage\n2. Click on the button\n3. See the error"
    validations:
      required: true
  - type: checkboxes
    id: tests-and-docs
    attributes:
      label: Tests and Documentation
      description: Have you added/updated tests and documentation (CHANGELOG?) for this bug fix?
      options:
        - label: I have added/updated tests for this bug fix
          required: true
        - label: I have added documentation for this bug fix
          required: true
        - label: I have updated the versioning
          required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/mrlunchbox777/basic-setup/tree/main/.github/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
