name: Chore Completion
description: Complete a chore
title: "[Chore]: "
labels: ["chore", "triage"]
projects: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for contributing and completing this chore!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: true
  - type: textarea
    id: chore-issue
    attributes:
      label: Issue Id
      description: What issue are you addressing with this PR?
      placeholder: Give us the issue number or a link to the issue
      value: "https://github.com/mrlunchbox777/basic-setup/issues/50"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: A Description of the Chore
      description: Please describe how this PR completes the chore
      placeholder: Let us know what you did to complete the chore
      value: "This PR completes the chore by renovating the dependencies in the project"
    validations:
      required: false
  - type: textarea
    id: steps
    attributes:
      label: Steps to Test
      description: How can we test the chore you're requesting?
      placeholder: Give us a step-by-step guide to test the chore. If the chore is not testable, please provide a reason. A link to steps in the issue is also acceptable.
      value: "1. Build the project\n2. Run the tests\n3. See the chore completed"
    validations:
      required: true
  - type: checkboxes
    id: tests-and-docs
    attributes:
      label: Tests and Documentation
      description: Have you added/updated tests and documentation (CHANGELOG?) for this chore?
      options:
        - label: I have added/updated tests for this chore
          required: true
        - label: I have added documentation for this chore
          required: true
        - label: I have updated the versioning
          required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/mrlunchbox777/basic-setup/tree/main/.github/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
