blank_issues_enabled: false
contact_links:
  - name: Bug Fix
    url: https://github.com/mrlunchbox777/basic-setup/compare/?template=bug.yaml
    about: Create a pull request to fix a bug here.
  - name: Feature Implementation
    url: https://github.com/mrlunchbox777/basic-setup/compare?template=feature.yaml
    about: Create a pull request to implement a feature here.
  - name: Chore Completion
    url: https://github.com/mrlunchbox777/basic-setup/compare?template=chore.yaml
  - name: Security Vulnerability Patch
    url: https://github.com/mrlunchbox777/basic-setup/compare?template=security.yaml
    about: Create a pull request to patch a security vulnerability here.
  - name: Documentation Update
    url: https://github.com/mrlunchbox777/basic-setup/compare?template=docs.yaml
    about: Create a pull request to update documentation here.
