# TODO: finish this
name: Documentation Update
description: Adding or updating documentation
title: "[Docs]: "
labels: ["documentation", "triage"]
projects: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for contributing and updating the documentation!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: true
  - type: textarea
    id: docs-issue
    attributes:
      label: Issue Id
      description: What issue are you addressing with this PR?
      placeholder: Give us the issue number or a link to the issue
      value: "https://github.com/mrlunchbox777/basic-setup/issues/50"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: A Description of the changes to the documentation
      description: Please describe how this PR improves the documentation
      placeholder: Let us know what you did and why
      value: "This PR improves the documentation by adding a new section to the README"
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/mrlunchbox777/basic-setup/tree/main/.github/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
