name: Feature Implementation
description: Adding a new feature to the codebase
title: "[Feature]: "
labels: ["feature", "triage"]
projects: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for contributing and adding this feature!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: true
  - type: textarea
    id: feature-issue
    attributes:
      label: Issue Id
      description: What issue are you addressing with this PR?
      placeholder: Give us the issue number or a link to the issue
      value: "https://github.com/mrlunchbox777/basic-setup/issues/50"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: A Description of the Feature Implementation
      description: Please describe how this PR implements the feature
      placeholder: Let us know what you did to implement the feature
      value: "This PR implements the feature by adding a new button to the homepage"
    validations:
      required: false
  - type: textarea
    id: steps
    attributes:
      label: Steps to Test
      description: How can we test the feature you're adding?
      placeholder: Give us a step-by-step guide to test the feature. A link to steps in the issue is also acceptable.
      value: "1. Go to the homepage\n2. Click on the button\n3. See the new feature"
    validations:
      required: true
  - type: checkboxes
    id: tests-and-docs
    attributes:
      label: Tests and Documentation
      description: Have you added/updated tests and documentation (CHANGELOG?) for this feature?
      options:
        - label: I have added/updated tests for this feature
          required: true
        - label: I have added documentation for this feature
          required: true
        - label: I have updated the versioning
          required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/mrlunchbox777/basic-setup/tree/main/.github/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
