apiVersion: v1
kind: Pod
metadata:
  labels:
    app: "$POD_NAME"
    app.kubernetes.io/name: "node-shell"
    app.kubernetes.io/instance: "$POD_NAME"
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: "node-shell"
    app.kubernetes.io/part-of: "node-shell"
    app.kubernetes.io/managed-by: "basic-setup"
  name: "$POD_NAME"
  namespace: "$NAMESPACE"

spec:
  containers:
    - args:
        - "-t"
        - "1"
        - "-m"
        - "-u"
        - "-i"
        - "-n"
        - "sleep"
        - "14000"
      command:
        - "nsenter"
      image: "$IMAGE_TO_USE"
      name: "$POD_NAME"
      resources:
        limits:
          cpu: 500m
          memory: 128Mi
      securityContext:
        privileged: true
  dnsPolicy: ClusterFirst
  hostPID: true
  hostIPC: true
  hostNetwork: true
  nodeSelector:
    "kubernetes.io/hostname": "$NODE_NAME"
  restartPolicy: "Never"
  terminationGracePeriodSeconds: 0
  tolerations:
    - operator: "Exists"
