apiVersion: v1
kind: Pod
metadata:
  labels:
    app: "$POD_NAME"
    app.kubernetes.io/name: "test-pod"
    app.kubernetes.io/instance: "$POD_NAME"
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: "test-pod"
    app.kubernetes.io/part-of: "test-pod"
    app.kubernetes.io/managed-by: "basic-setup"
  name: "$POD_NAME"
  namespace: "$NAMESPACE"

spec:
  containers:
    - args:
        - "-f"
        - "/dev/null"
      command:
        - "tail"
      image: "$IMAGE_TO_USE"
      name: "$POD_NAME"
      resources:
        limits:
          cpu: 500m
          memory: 128Mi
      securityContext:
        privileged: true
  restartPolicy: "Never"
  terminationGracePeriodSeconds: 0
  tolerations:
    - operator: "Exists"
