blank_issues_enabled: false
contact_links:
  - name: Bug Report
    url: https://github.com/mrlunchbox777/basic-setup/issues/new?template=bug.yaml
    about: Please report bugs here.
  - name: Feature Request
    url: https://github.com/mrlunchbox777/basic-setup/issues/new?template=feature.yaml
    about: Please request new features here.
  - name: Chore Request
    url: https://github.com/mrlunchbox777/basic-setup/issues/new?template=chore.yaml
    about: Please request chores here.
  - name: Support Request
    url: https://github.com/mrlunchbox777/basic-setup/issues/new?template=support.yaml
    about: Please request support here.
  - name: Security Vulnerability Report
    url: https://github.com/mrlunchbox777/basic-setup/issues/new?template=security.yaml
    about: Please report security vulnerabilities here.
  - name: Missing Attribution Report
    url: https://github.com/mrlunchbox777/basic-setup/issues/new?template=attribution.yaml
    about: Please report missing attribution here.
