name: Feature Request
description: File a feature request
title: "feature: "
labels: ["kind/feature", "status/triage"]
assignees:
  - mrlunchbox777
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: What feature are you requesting?
      placeholder: Tell us, in summary, what you want added or changed!
  - type: textarea
    id: why
    attributes:
      label: Why?
      description: Why do you think this feature should be added?
      placeholder: Tell us why you think this feature should be added!
    validations:
      required: true
  - type: textarea
    id: what-should-happen
    attributes:
      label: What should happen?
      description: What feature are you requesting? Please include as much detail as possible.
      placeholder: Tell us, in detail, what you want added or changed!
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Test
      description: How can we test the feature you're requesting? In other words, what acceptance criteria should be met?
      placeholder: Give us a step-by-step guide to test the feature. If the feature is not testable, please provide a reason.
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/mrlunchbox777/basic-setup/tree/main/.github/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
