name: Support Request
description: File a support request
title: "support: "
labels: ["support", "triage"]
assignees:
  - mrlunchbox777
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this support request!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of the software are you using?
      placeholder: ex. 1.0.0
    validations:
      required: true
  - type: input
    id: environment
    attributes:
      label: Environment
      description: What environment are you using?
      placeholder: ex. Windows 10, MacOS 11.0.1, Ubuntu 24.04
    validations:
      required: true
  - type: input
    id: description
    attributes:
      label: Support Description
      description: What, in summary, do you need help with?
      placeholder: Tell us what you see!
  - type: textarea
    id: what-is-needed
    attributes:
      label: Support Details
      description: What do you need help with? Please include as much detail as possible.
      placeholder: Tell us what you need!
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/mrlunchbox777/basic-setup/tree/main/.github/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
