apiVersion: v1
kind: Pod
metadata:
  labels:
    app: pod_name
  name: pod_name
  namespace: "kube-system"
spec:
  containers:
  - args:
      - "-t"
      - "1"
      - "-m"
      - "-u"
      - "-i"
      - "-n"
      - "sleep"
      - "14000"
    command:
      - "nsenter"
    image: BASIC_SETUP_APLINE_IMAGE_TO_USE
    name: pod_name
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
    securityContext:
      privileged: true
  dnsPolicy: ClusterFirst
  hostPID: true
  hostIPC: true
  hostNetwork: true
  nodeSelector:
    "kubernetes.io/hostname": "node_name"
  restartPolicy: "Never"
  terminationGracePeriodSeconds: 0
  tolerations:
    - operator: "Exists"
