apiVersion: v1
kind: Pod
metadata:
  labels:
    app: $pod_name
  name: $pod_name
  namespace: "kube-system"

spec:
  containers:
  - args:
      - "-f"
      - "/dev/null"
    command:
      - "tail"
    image: $BASIC_SETUP_BASH_IMAGE_TO_USE
    name: $pod_name
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
    securityContext:
      privileged: true
  restartPolicy: "Never"
  terminationGracePeriodSeconds: 0
  tolerations:
    - operator: "Exists"
